language: python

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"

script:
    - "coverage run --source=wsstat setup.py test"

after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash)
